[build]
  functions = "netlify/functions"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[headers]]
  for = "/netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
